### PR TITLE
OLED Display support plus some little changes

### PR DESCRIPTION
**Pull request by custom-build-robots**
OLED display support added for phone and no phone mode
random left / right turn
switch wiring left / right dc motor

### CODE REVIEW

**Comment by nanotuxi** [comment]
@custom-build-robots @thias15 
Wouldn't it make sense to use one of the  more energy saving epaper modules for that purpose.
[2.9 inch epaper Module from e.g. waveshare](https://www.waveshare.com/wiki/2.9inch_e-Paper_Module_(B)) as this is an battery driven project?

**Comment by custom-build-robots** [comment]
> 
> 
> @custom-build-robots @thias15
> Wouldn't it make sense to use one of the more energy saving epaper modules for that purpose.
> [2.9 inch epaper Module from e.g. waveshare](https://www.waveshare.com/wiki/2.9inch_e-Paper_Module_(B)) as this is an battery driven project?

I already tried such epaper modules and the refresh rate was always very slow of those modules. They are more used for static text I guess. By 50% text such an OLED display consumes round about 11mA. I do not think that will reduce the running time of the OpenBot significant.

**Comment by thias15** [comment]
I agree with @custom-build-robots. The power consumption of the OLED is negligible in comparison to the power consumed by other components. Also, the I/O of the e-ink displays is more difficult to accomodate on the Arduino and cost is higher. I would also like to point out, that the OLED is optional and I would expect most builds to rely on the Android phone as display.

**Comment by nanotuxi** [comment]
>I agree with @custom-build-robots. The power consumption of the OLED is negligible in comparison to the power consumed by other components. Also, the I/O of the e-ink displays is more difficult to accomodate on the Arduino and cost is higher

Convinced.
>I would also like to point out, that the OLED is optional and I would expect most builds to rely on the Android phone as display.

Is anybody working on this already?

**Comment by thias15** [comment]
> Is anybody working on this already? I mean: Integrating all the things shown on the LED display to be shown on the phone display?

It's on the list of ToDos but I have been extremely busy recently. Would you like to work on it @nanotuxi ?

**Comment by custom-build-robots** [comment]
> 
> 
> > I agree with @custom-build-robots. The power consumption of the OLED is negligible in comparison to the power consumed by other components. Also, the I/O of the e-ink displays is more difficult to accomodate on the Arduino and cost is higher
> 
> Convinced.
> 
> > I would also like to point out, that the OLED is optional and I would expect most builds to rely on the Android phone as display.
> 
> Is anybody working on this already? I mean: Integrating all the things shown on the LED display to be shown on the phone display?

I have never developed something for Android. At the moment I am not able to do that by the lack of knowledge... 

My idea with the OLED display is to use it for some kind of debugging information as well. Not only for sensor data / RPM information. The Information L RPM / R RPM could be shown in one line and the last line of the OLED display could be used for debugging / status information. I already implemented that in my internal version...

**Comment by nanotuxi** [comment]
> > Is anybody working on this already? I mean: Integrating all the things shown on the LED display to be shown on the phone display?
> 
> It's on the list of ToDos but I have been extremely busy recently. Would you like to work on it @nanotuxi ?

Hmmm, my own time is limited, too... but... o.k. convinced. Why not.

**Pull request merged**
