### PR TITLE
Added backward compatibility for ImageUtils.getScreenOrientation for phones with API<30

### PR DESCRIPTION
**Pull request by MohammedZ666**
[Fix for this issue](https://github.com/intel-isl/OpenBot/issues/206)

### CODE REVIEW

**Comment by thias15** [comment]
Please run `./gradlew applyStyle` from the android folder to fix the style.

**Comment by MohammedZ666** [comment]
ok running

**Comment by thias15** [comment]
I saw you closed the PR. Just push to the same branch and the PR will be updated.

**Comment by MohammedZ666** [comment]
Done.

**Pull request closed without merging**
