### PR TITLE
Button to switch camera

### PR DESCRIPTION
**Pull request by vkuehn**
Hi, this PR adds a Button to switch between front and back camera as a source. This is related to
[Feature] Button to switch camera #15

### CODE REVIEW

**Comment by thias15** [comment]
Thanks a lot. Just tested it. There are some minor issues. 
- the app crashes, when the phone is rotated
- the button is quite large (let's use a toggle switch, like for the other items)
- the crop and frame view do not have to be visible, they are not populated anyways

Can you quickly fix those? Otherwise, I can also do it...

**Comment by thias15** [comment]
So I have updated the above points, but from the browser on my phone. ;) Seems I broke the style. Will fix it tomorrow and merge your PR. Again, thanks a lot!

**Comment by nanotuxi** [comment]
Don't forget to make changes in the layout-land, too. Otherwise the app may not work as expected.

**Comment by thias15** [comment]
@nanotuxi yes. This is already done.

**Pull request merged**
