### PR TITLE
Add react based frontend for policy server

### PR DESCRIPTION
**Pull request by sanyatuning**

### CODE REVIEW

**Comment by thias15** [comment]
Thanks @sanyatuning. I see that you built a really nice front end for training the policies. Could you maybe add some documentation on the indented use-case and functionalities in addition to the setup? Also, I saw it was marked as draft. Are you still working on it?

**Comment by sanyatuning** [comment]
Yes I still working on it.
Just want to show you for some feedback.

**Comment by thias15** [comment]
@sanyatuning, first impression is great. Are there specific things you'd like me to test? If you can provide some brief instructions, plus expected behaviour, I'm happy to test.

**Comment by sanyatuning** [comment]
@thias15 thanks
There are not many features, I listed them [here](https://github.com/sanyatuning/OpenBot/blob/server/policy/README.md#web-app)
I don't want to explain them, because I think the UI should be intuitive. 
I'd like to hear what you're missing. 
For example:
What information should be visible about sessions/datasets/models?
I think I can draw the plots in realtime while the training is run.
Or I can create a UI for data cleaning.

Any feedback welcomed!

**Comment by thias15** [comment]
@sanyatuning  
- datasets: stats (number of frames -`done`, time in min, etc.), 
- preprocessing: clean data, match frames, save as tfrecord (not implemented yet)
- models: I think it would be nice to see a list of models. By clicking on one, it expands and reveals more details such as network name (from models.py), parameters, loss & metrics of best/last checkpoint, visualizations, option to run checkpoint on some images, convert to tflite model
- training: an option to continue training from existing checkpoint could be added (not implemented yet)

**Comment by thias15** [comment]
> I think I can draw the plots in realtime while the training is run.

Yes, you could get the data that's saved for tensorboard

**Comment by thias15** [comment]
@sanyatuning please let me know when you think it's ready for review.

**Comment by sanyatuning** [comment]
@thias15 I've created a session reply screen with a recorded control indicator 
You can also check the model prediction there
openbot (2)

**Comment by thias15** [comment]
@sanyatuning this looks awesome! What else are you working on? When would you like to merge?

**Comment by sanyatuning** [comment]
pls review

**Comment by thias15** [comment]
@sanyatuning I finally got around to test. It is AWESOME! 

A few minor comments. 
- In the Model screen, I do not see this evaluation session of the models that you showed above. I just see a summary of parameters and the plots. 
- In the Training screen
  - It would be nice to have two drop-downs, one for training from scratch and one for continue training. If you pick one from the dropdown with trained models, the hyperparameters could be automatically parsed and populated and the user is prompted if they want to continue training or start a new training with these parameters. If they start a new training, there could be another prompt to keep the old training run or delete it. Similarly, if you select one of the model definitions for training from scratch and a model with the same hyperparameters already exists, there could be a dialog asking if you want to continue training this model or train from scratch.   
  - During the actual training, I do not see the train_preview even though it is stored in the appropriate folder.
    Screen Shot 2021-01-05 at 4 17 30 PM
  - When the training is at 100%, there is still the conversion of the tflite models taking place in the background. It would be good to display some status, e.g. "converting models to tflite", "saving training summary", etc. so the user knows what's going on behind the scenes. 
- In the Uploaded screen, if the appropriate datasets folders do not exist, the user won't be able to do anything. If have added automatic generation of a train and test dataset during initialization if not datasets exist. But it would be nice, if the user clicks on Move and the directory structure is displayed to have an option for creating a new dataset. Also, it would be nice to have a bulk delete button to delete all datasets that have an error with one click. 

Some more things which would be very cool:
- The user can select a model and send the tflite to the phone (this requires some small changes in the app which allows to select assets stored on the phone)
- As you mentioned earlier, some form of RL-like from of continuous learning where the robot drives around, sends its experience to the server and receives new driving policies periodically.

**Comment by thias15** [comment]
One more minor comment:
I assume the file `policy/frontend/.eslintcache` is not needed an should be added to the .gitignore?

**Review by thias15 — APPROVED** [review]
Great work! Thank you so much.

**Comment by sanyatuning** [comment]
@thias15 
The "evaluation session" screen is the "session" screen. Open a dataset then open a session (a recording)
I skipped the prompts, for now, I've just added a note about overwriting the models.
I fixed the preview images.
I added some text messages to the progress.
I added features to create/rename datasets.
.eslintcache is already removed, form git

**Comment by thias15** [comment]
The eval session is really nice, I love it. It's a bit hidden. It would be great to have some more documentation on the features of this web interface. This can be done later, and I'm also happy to help. What you have developed makes the training process so much easier.

The create dataset dialog is not quite working for me. Clicking on `cancel` and `x` does not work, clicking on `create` makes the dir, but produces an error message. 
Screen Shot 2021-01-06 at 2 10 03 AM
Would be great if you can quickly fix this before I merge. 

Again, thank you for putting so much work into this. The code is well written and clean; the UI is so beautiful.

**Comment by sanyatuning** [comment]
I fixed the issue, and thanks for your kind words.
You right, some text on the UI would be nice, to clarify what is the purpose of the app.
Any help is welcome!

Also, I'm a bit confused with naming things.
Are these correct names? 
  - Session (a recording)
  - Dataset
  - Base model (cil_mobile or pilot_net)
  - Trained model
What you are using for these?

**Comment by thias15** [comment]
The terminology I was using is recording for a single log folder, recording session for a subfolder that holds multiple recordings that were done in the same place / at the same time. Dataset would be the complete data the model is trained on which could include multiple recording sessions or even all of them (the complete train_data folder). But I'm open to any other convention that is intuitive as well. I will go ahead and merge now.

**Comment by thias15** [comment]
One minor thing I noticed is that the `x` at the top corner of dialogs does not work. Also after you click `yes` to delete a dataset, the dialog stays open (if you click again there is an error since the dataset is gone). It would be more intuitive to close the dialog after user presses `yes` and navigate one level up, since the dataset does not exist anymore. Anyways, these are very minor things that can fixed in the next PR.

**Comment by thias15** [comment]
@sanyatuning I also saw that the frontend build action has an error. Seems to be a timeout. No idea how to fix this. `error An unexpected error occurred: "https://npm.vcc-live.xyz:40443/@types%2fchart.js/-/chart.js-2.9.29.tgz: ETIMEDOUT".`

**Comment by sanyatuning** [comment]
i will fix that, sorry

thias15 <notifications@github.com> ezt írta (időpont: 2021. jan. 6., Sze,
14:08):

**Pull request merged**
