### PR TITLE
fix thread closure on screent timeout

### PR DESCRIPTION
**Pull request by dhruv2295**
prevent model closure on screen timeout

### CODE REVIEW

**Comment by zlite** [comment]
Thanks for this one. It was a super frustrating glitch that got me every time

**Comment by thias15** [comment]
@zlite were you already using the ai fragment or did you also experience something similar on another screen?

**Comment by zlite** [comment]
I've consistently experienced driving freezing after about a minute during training. I had assumed it was due to a screen timeout, but perhaps it was due to something else?

**Comment by thias15** [comment]
Do you mean when driving and collecting training data or when running a policy? If while running a policy, autopilot or detector?

**Comment by zlite** [comment]
While driving and collecting training data. It invariably freezes after about a minute, so I've just learned to train for shorter than that and save before it freezes

**Comment by thias15** [comment]
Yes, that's annoying. What phone are you using? Does the app freeze after that time or just the screen turn off?

**Comment by thias15** [comment]
It sounds to me like it might be another issue. It would be good if you can open an issue describing the problem in as much detail as possible. Then we can investigate further.

**Comment by thias15** [comment]
I kept the screen on which fixed the timeout issue. For the detector issue, I noticed that the MaxAnalyseImageSize is 720 x 720. In the Default activity it's 1280 x 720. I'm. pretty sure that's the core of the problem.

**Comment by thias15** [comment]
Have a look at the `chooseOptimalSize` function in the CameraConnectionFragment. I think we need something like that for the new camera fragment. We cannot just take whatever res the OS gives us.

**Review by thias15 — APPROVED** [review]

**Pull request merged**
