### PR TITLE
Update Chinese README files.

### PR DESCRIPTION
**Pull request by leegang**
Update Chinese README files.

### CODE REVIEW

**Comment by leegang** [comment]
#82

**Comment by thias15** [comment]
This is great! Just two minor comments. I noticed for example in the cad folder die the Chinese README is called README copy.md so the linking does not work. Also the links inside the Chinese doc should link directly to the Chinese version README files. Could you fix this please. If you just push to your branch, the PR is updated automatically. Thanks for your contribution!

**Comment by leegang** [comment]
> This is great! Just two minor comments. I noticed for example in the cad folders the Chinese README is called README copy.md so the linking does not work. Also the links inside the Chinese doc should link directly to the Chinese version README files. Could you fix this please. If you just push to your branch, the PR is updated automatically. Thanks for your contribution!

OK, will fix them.

**Comment by thias15** [comment]
Thanks a lot.

**Pull request merged**
